import { TOOL_IDS } from '../../tools/toolConfigs.js'

const RJ45_MODULE_ID = 'rj45-cable-termination'
const ETHERNET_CABLE_ID = 'ethernet-cable'
const JACKET_STRIPPING_DURATION = 1.25
const JACKET_STRIPPING_WORK_END = 0.72
const TRIMMING_DURATION = 0.9
const CONNECTOR_ALIGNMENT_DURATION = 0.85
const CONNECTOR_INSERTION_DURATION = 1.15
const CONNECTOR_POSITIONING_DURATION = 0.9
const CRIMPING_DURATION = 1.25
const TESTER_CONNECTION_DURATION = 0.95
const CABLE_TEST_DURATION = 2
const RJ45_TOTAL_STEPS = 19

const RJ45_PROCEDURE_STEPS = Object.freeze({
  NOT_STARTED: 'not-started',
  SELECT_CABLE: 'select-cable',
  SELECT_WIRE_STRIPPER: 'select-wire-stripper',
  STRIP_JACKET: 'strip-jacket',
  JACKET_STRIPPED: 'jacket-stripped',
  COMPLETE_FOR_TASK_1: 'complete-for-task-1',
  SEPARATE_PAIRS: 'separate-pairs',
  PAIRS_SEPARATED: 'pairs-separated',
  ARRANGE_T568B: 'arrange-t568b',
  VALIDATE_T568B: 'validate-t568b',
  WIRES_ARRANGED: 'wires-arranged',
  COMPLETE_FOR_TASK_2: 'complete-for-task-2',
  SELECT_CUTTING_TOOL: 'select-cutting-tool',
  POSITION_FOR_TRIM: 'position-for-trim',
  TRIM_WIRES: 'trim-wires',
  TRIMMING: 'trimming',
  WIRES_TRIMMED: 'wires-trimmed',
  COMPLETE_FOR_TASK_3: 'complete-for-task-3',
  SELECT_RJ45_CONNECTOR: 'select-rj45-connector',
  ALIGN_CONNECTOR: 'align-connector',
  INSERT_CONDUCTORS: 'insert-conductors',
  INSERTING_CONDUCTORS: 'inserting-conductors',
  VERIFY_INSERTION: 'verify-insertion',
  CONDUCTORS_INSERTED: 'conductors-inserted',
  COMPLETE_FOR_TASK_4: 'complete-for-task-4',
  SELECT_CRIMPING_TOOL: 'select-crimping-tool',
  POSITION_CONNECTOR_IN_CRIMPER: 'position-connector-in-crimper',
  READY_TO_CRIMP: 'ready-to-crimp',
  CRIMPING: 'crimping',
  CRIMP_COMPLETE: 'crimp-complete',
  COMPLETE_FOR_TASK_5: 'complete-for-task-5',
  SELECT_CABLE_TESTER: 'select-cable-tester',
  CONNECT_CABLE_TO_TESTER: 'connect-cable-to-tester',
  READY_TO_TEST: 'ready-to-test',
  TESTING_CABLE: 'testing-cable',
  TEST_RESULT: 'test-result',
  RJ45_MODULE_COMPLETE: 'rj45-module-complete',
})

const rj45Procedure = Object.freeze({
  [RJ45_PROCEDURE_STEPS.NOT_STARTED]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.NOT_STARTED,
    stepNumber: 0,
    title: 'Ready to Begin',
    instruction: 'Select Begin Training to start the RJ45 procedure.',
    acceptedAction: 'begin-training',
  }),
  [RJ45_PROCEDURE_STEPS.SELECT_CABLE]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.SELECT_CABLE,
    stepNumber: 1,
    title: 'Select the Cable',
    instruction: 'Step 1: Select the Ethernet cable.',
    acceptedAction: 'select-workpiece',
    acceptedWorkpieceId: ETHERNET_CABLE_ID,
  }),
  [RJ45_PROCEDURE_STEPS.SELECT_WIRE_STRIPPER]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.SELECT_WIRE_STRIPPER,
    stepNumber: 2,
    title: 'Choose the Correct Tool',
    instruction: 'Step 2: Select the wire stripper.',
    acceptedAction: 'select-tool',
    acceptedToolId: TOOL_IDS.WIRE_STRIPPER,
  }),
  [RJ45_PROCEDURE_STEPS.STRIP_JACKET]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.STRIP_JACKET,
    stepNumber: 3,
    title: 'Remove the Outer Jacket',
    instruction: 'Step 3: Use the wire stripper on the Ethernet cable.',
    acceptedAction: 'strip-jacket',
    acceptedToolId: TOOL_IDS.WIRE_STRIPPER,
    acceptedWorkpieceId: ETHERNET_CABLE_ID,
  }),
  [RJ45_PROCEDURE_STEPS.JACKET_STRIPPED]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.JACKET_STRIPPED,
    stepNumber: 3,
    title: 'Jacket Removed',
    instruction: 'Jacket removed successfully.',
    acceptedAction: 'continue',
  }),
  [RJ45_PROCEDURE_STEPS.COMPLETE_FOR_TASK_1]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.COMPLETE_FOR_TASK_1,
    stepNumber: 3,
    title: 'Jacket Removed',
    instruction: 'Jacket removed successfully.',
    nextInstruction: 'Next procedure: Arrange the wire pairs.',
    acceptedAction: 'continue',
  }),
  [RJ45_PROCEDURE_STEPS.SEPARATE_PAIRS]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.SEPARATE_PAIRS,
    stepNumber: 4,
    title: 'Separate the Wire Pairs',
    instruction: 'Step 4: Separate the wire pairs.',
    acceptedAction: 'separate-pairs',
  }),
  [RJ45_PROCEDURE_STEPS.PAIRS_SEPARATED]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.PAIRS_SEPARATED,
    stepNumber: 4,
    title: 'Wire Pairs Separated',
    instruction: 'The exposed wire pairs are ready for arrangement.',
    acceptedAction: null,
  }),
  [RJ45_PROCEDURE_STEPS.ARRANGE_T568B]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.ARRANGE_T568B,
    stepNumber: 5,
    title: 'Arrange the Conductors',
    instruction: 'Step 5: Arrange the wires using the T568B standard.',
    acceptedAction: 'arrange-wires',
  }),
  [RJ45_PROCEDURE_STEPS.VALIDATE_T568B]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.VALIDATE_T568B,
    stepNumber: 5,
    title: 'Validate the Arrangement',
    instruction: 'Step 5: Validate the completed T568B wire order.',
    acceptedAction: 'validate-wires',
  }),
  [RJ45_PROCEDURE_STEPS.WIRES_ARRANGED]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.WIRES_ARRANGED,
    stepNumber: 5,
    title: 'Wires Arranged',
    instruction: 'Correct T568B arrangement.',
    acceptedAction: 'continue',
  }),
  [RJ45_PROCEDURE_STEPS.COMPLETE_FOR_TASK_2]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.COMPLETE_FOR_TASK_2,
    stepNumber: 5,
    title: 'T568B Arrangement Complete',
    instruction: 'Correct T568B arrangement.',
    acceptedAction: 'continue',
  }),
  [RJ45_PROCEDURE_STEPS.SELECT_CUTTING_TOOL]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.SELECT_CUTTING_TOOL,
    stepNumber: 6,
    title: 'Select the Cutting Tool',
    instruction:
      'Step 6: Select the crimping tool to trim the wire ends evenly.',
    acceptedAction: 'select-tool',
    acceptedToolId: TOOL_IDS.CRIMPING_TOOL,
  }),
  [RJ45_PROCEDURE_STEPS.POSITION_FOR_TRIM]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.POSITION_FOR_TRIM,
    stepNumber: 7,
    title: 'Position the Conductors',
    instruction: 'Step 7: Position the conductors against the trim guide.',
    acceptedAction: 'trim-wires',
    acceptedToolId: TOOL_IDS.CRIMPING_TOOL,
  }),
  [RJ45_PROCEDURE_STEPS.TRIM_WIRES]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.TRIM_WIRES,
    stepNumber: 7,
    title: 'Trim the Conductors',
    instruction: 'Step 7: Trim all eight conductors at the cutting line.',
    acceptedAction: 'trim-wires',
    acceptedToolId: TOOL_IDS.CRIMPING_TOOL,
  }),
  [RJ45_PROCEDURE_STEPS.TRIMMING]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.TRIMMING,
    stepNumber: 7,
    title: 'Trimming the Conductors',
    instruction: 'Trimming the conductor ends evenly...',
    acceptedAction: null,
  }),
  [RJ45_PROCEDURE_STEPS.WIRES_TRIMMED]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.WIRES_TRIMMED,
    stepNumber: 8,
    title: 'Conductors Trimmed',
    instruction: 'Step 8: Conductors trimmed evenly.',
    acceptedAction: 'continue',
  }),
  [RJ45_PROCEDURE_STEPS.COMPLETE_FOR_TASK_3]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.COMPLETE_FOR_TASK_3,
    stepNumber: 8,
    title: 'Conductors Trimmed',
    instruction: 'Step 8: Conductors trimmed evenly.',
    acceptedAction: 'continue',
  }),
  [RJ45_PROCEDURE_STEPS.SELECT_RJ45_CONNECTOR]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.SELECT_RJ45_CONNECTOR,
    stepNumber: 9,
    title: 'Select the Connector',
    instruction: 'Step 9: Select the RJ45 connector.',
    acceptedAction: 'select-tool',
    acceptedToolId: TOOL_IDS.RJ45_CONNECTOR,
  }),
  [RJ45_PROCEDURE_STEPS.ALIGN_CONNECTOR]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.ALIGN_CONNECTOR,
    stepNumber: 10,
    title: 'Align the Connector',
    instruction: 'Step 10: Align the connector with the conductors.',
    acceptedAction: 'align-connector',
    acceptedToolId: TOOL_IDS.RJ45_CONNECTOR,
  }),
  [RJ45_PROCEDURE_STEPS.INSERT_CONDUCTORS]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.INSERT_CONDUCTORS,
    stepNumber: 10,
    title: 'Insert the Conductors',
    instruction: 'Step 10: Insert the conductors into the connector channels.',
    acceptedAction: 'insert-conductors',
    acceptedToolId: TOOL_IDS.RJ45_CONNECTOR,
  }),
  [RJ45_PROCEDURE_STEPS.INSERTING_CONDUCTORS]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.INSERTING_CONDUCTORS,
    stepNumber: 10,
    title: 'Inserting the Conductors',
    instruction: 'Inserting all eight conductors into their channels...',
    acceptedAction: null,
  }),
  [RJ45_PROCEDURE_STEPS.VERIFY_INSERTION]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.VERIFY_INSERTION,
    stepNumber: 10,
    title: 'Verify the Insertion',
    instruction: 'Verifying conductor depth and cable jacket position.',
    acceptedAction: 'verify-insertion',
  }),
  [RJ45_PROCEDURE_STEPS.CONDUCTORS_INSERTED]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.CONDUCTORS_INSERTED,
    stepNumber: 11,
    title: 'Connector Insertion Complete',
    instruction: 'Step 11: Connector insertion complete.',
    acceptedAction: 'continue',
  }),
  [RJ45_PROCEDURE_STEPS.COMPLETE_FOR_TASK_4]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.COMPLETE_FOR_TASK_4,
    stepNumber: 11,
    title: 'Connector Insertion Complete',
    instruction: 'Step 11: Connector insertion complete.',
    nextInstruction: 'Next procedure: Crimp the RJ45 connector.',
    acceptedAction: 'continue',
  }),
  [RJ45_PROCEDURE_STEPS.SELECT_CRIMPING_TOOL]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.SELECT_CRIMPING_TOOL,
    stepNumber: 12,
    title: 'Select the Crimping Tool',
    instruction: 'Step 12: Select the crimping tool.',
    acceptedAction: 'select-tool',
    acceptedToolId: TOOL_IDS.CRIMPING_TOOL,
  }),
  [RJ45_PROCEDURE_STEPS.POSITION_CONNECTOR_IN_CRIMPER]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.POSITION_CONNECTOR_IN_CRIMPER,
    stepNumber: 13,
    title: 'Position the Connector',
    instruction:
      'Step 13: Position the RJ45 connector inside the crimping slot.',
    acceptedAction: 'position-connector',
    acceptedToolId: TOOL_IDS.CRIMPING_TOOL,
  }),
  [RJ45_PROCEDURE_STEPS.READY_TO_CRIMP]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.READY_TO_CRIMP,
    stepNumber: 14,
    title: 'Crimp the Connector',
    instruction: 'Step 14: Squeeze the crimping tool handles.',
    acceptedAction: 'crimp-connector',
    acceptedToolId: TOOL_IDS.CRIMPING_TOOL,
  }),
  [RJ45_PROCEDURE_STEPS.CRIMPING]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.CRIMPING,
    stepNumber: 14,
    title: 'Crimping the Connector',
    instruction: 'Pressing the contacts and securing the strain relief...',
    acceptedAction: null,
  }),
  [RJ45_PROCEDURE_STEPS.CRIMP_COMPLETE]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.CRIMP_COMPLETE,
    stepNumber: 15,
    title: 'Crimp Complete',
    instruction: 'Crimp completed successfully.',
    acceptedAction: 'continue',
  }),
  [RJ45_PROCEDURE_STEPS.COMPLETE_FOR_TASK_5]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.COMPLETE_FOR_TASK_5,
    stepNumber: 15,
    title: 'Crimp Complete',
    instruction: 'Crimp completed successfully.',
    acceptedAction: 'continue',
  }),
  [RJ45_PROCEDURE_STEPS.SELECT_CABLE_TESTER]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.SELECT_CABLE_TESTER,
    stepNumber: 16,
    title: 'Select the Cable Tester',
    instruction: 'Step 16: Select the cable tester.',
    acceptedAction: 'select-tool',
    acceptedToolId: TOOL_IDS.CABLE_TESTER,
  }),
  [RJ45_PROCEDURE_STEPS.CONNECT_CABLE_TO_TESTER]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.CONNECT_CABLE_TO_TESTER,
    stepNumber: 17,
    title: 'Connect the Cable',
    instruction: 'Step 17: Connect the terminated cable to the tester.',
    acceptedAction: 'connect-cable',
    acceptedToolId: TOOL_IDS.CABLE_TESTER,
  }),
  [RJ45_PROCEDURE_STEPS.READY_TO_TEST]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.READY_TO_TEST,
    stepNumber: 18,
    title: 'Run the Cable Test',
    instruction: 'Step 18: Run the cable test.',
    acceptedAction: 'test-cable',
    acceptedToolId: TOOL_IDS.CABLE_TESTER,
  }),
  [RJ45_PROCEDURE_STEPS.TESTING_CABLE]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.TESTING_CABLE,
    stepNumber: 18,
    title: 'Testing Cable',
    instruction: 'Checking continuity from Pin 1 through Pin 8...',
    acceptedAction: null,
  }),
  [RJ45_PROCEDURE_STEPS.TEST_RESULT]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.TEST_RESULT,
    stepNumber: 19,
    title: 'Cable Test Complete',
    instruction: 'Test Result: PASS',
    acceptedAction: null,
  }),
  [RJ45_PROCEDURE_STEPS.RJ45_MODULE_COMPLETE]: Object.freeze({
    id: RJ45_PROCEDURE_STEPS.RJ45_MODULE_COMPLETE,
    stepNumber: 19,
    title: 'Module Complete',
    instruction: 'RJ45 cable termination completed successfully.',
    acceptedAction: null,
  }),
})

function getRJ45ProcedureStep(stepId) {
  return rj45Procedure[stepId] ?? rj45Procedure[RJ45_PROCEDURE_STEPS.NOT_STARTED]
}

export {
  CABLE_TEST_DURATION,
  CONNECTOR_ALIGNMENT_DURATION,
  CONNECTOR_INSERTION_DURATION,
  CONNECTOR_POSITIONING_DURATION,
  CRIMPING_DURATION,
  ETHERNET_CABLE_ID,
  getRJ45ProcedureStep,
  JACKET_STRIPPING_DURATION,
  JACKET_STRIPPING_WORK_END,
  RJ45_MODULE_ID,
  RJ45_PROCEDURE_STEPS,
  RJ45_TOTAL_STEPS,
  TESTER_CONNECTION_DURATION,
  TRIMMING_DURATION,
  rj45Procedure,
}
